export const exportToPDF = (inputText: string, translatedText: string, isReverse: boolean) => {
  const printWindow = window.open('', '', 'width=800,height=800');
  if (!printWindow) throw new Error('Please allow popups to generate PDF');
  
  printWindow.document.write(`
    <html>
      <head>
        <title>MOZHIYON - Translation Export</title>
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #111; line-height: 1.6; }
          .header { border-bottom: 2px solid #8B0000; padding-bottom: 10px; margin-bottom: 30px; }
          h1 { color: #8B0000; font-family: serif; letter-spacing: 2px; }
          .label { font-size: 12px; font-weight: bold; color: #888; text-transform: uppercase; letter-spacing: 1px; }
          .content { font-size: 18px; margin-bottom: 40px; }
          .tamil { font-size: 24px; }
          .footer { margin-top: 50px; font-size: 12px; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>MOZHIYON</h1>
          <p>Generated Translation Document</p>
        </div>
        <div class="label">${isReverse ? 'Original Tamil:' : 'Original English:'}</div>
        <div class="content">${inputText.replace(/\n/g, '<br/>')}</div>
        
        <div class="label">${isReverse ? 'Translated English:' : 'Translated Tamil:'}</div>
        <div class="content tamil">${translatedText.replace(/\n/g, '<br/>')}</div>
        
        <div class="footer">
          Generated by MOZHIYON Translation Service on ${new Date().toLocaleString()}
        </div>
      </body>
    </html>
  `);
  printWindow.document.close();
  setTimeout(() => {
    printWindow.print();
  }, 500);
};

export const exportToAudio = (text: string, lang: string) => {
  try {
    const url = `https://translate.google.com/translate_tts?ie=UTF-8&tl=${lang}&client=tw-ob&q=${encodeURIComponent(text)}`;
    const a = document.createElement('a');
    a.href = url;
    a.target = '_blank';
    a.download = `mozhiyon-audio-${Date.now()}.mp3`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  } catch (error) {
    throw error;
  }
};

export const exportToSRT = (text: string) => {
  const words = text.split(/\s+/).filter(Boolean);
  const CHUNK_SIZE = 8;
  let srtContent = "";
  let counter = 1;
  let startTime = 0;

  for (let i = 0; i < words.length; i += CHUNK_SIZE) {
    const chunk = words.slice(i, i + CHUNK_SIZE).join(' ');
    const endTime = startTime + 3; // 3 seconds per chunk

    const formatTime = (seconds: number) => {
      const h = Math.floor(seconds / 3600).toString().padStart(2, '0');
      const m = Math.floor((seconds % 3600) / 60).toString().padStart(2, '0');
      const s = (seconds % 60).toString().padStart(2, '0');
      return `${h}:${m}:${s},000`;
    };

    srtContent += `${counter}\n`;
    srtContent += `${formatTime(startTime)} --> ${formatTime(endTime)}\n`;
    srtContent += `${chunk}\n\n`;

    startTime = endTime;
    counter++;
  }

  const blob = new Blob([srtContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Mozhiyon_Subtitles_${Date.now()}.srt`;
  a.click();
  URL.revokeObjectURL(url);
};
